DROP TABLE IF EXISTS movie;
DROP TABLE IF EXISTS awards;

CREATE TABLE movie (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    YEARS INTEGER,
    TITLE VARCHAR(255),
    STUDIOS VARCHAR(255),
    PRODUCERS VARCHAR(255),
    WINNER VARCHAR(255)
);
INSERT INTO movie (YEARS, TITLE, STUDIOS, PRODUCERS, WINNER) SELECT * FROM CSVREAD('classpath:movie.csv', null, 'fieldSeparator=;');

--> TEMP TABLE FOR DATA CLEAN UP https://stackoverflow.com/questions/5493510/turning-a-comma-separated-string-into-individual-rows
CREATE TABLE temp_table AS WITH tmp(years, winner, producers, name) AS
(
    SELECT
        YEARS,
        WINNER,
        SUBSTRING(producers, 1, POSITION(' and ' IN producers || ' and ') - 1),
        SUBSTRING(producers, POSITION(' and ' IN producers || ' and ') + 5)
    FROM movie

    UNION ALL

    SELECT
        YEARS,
        WINNER,
        SUBSTRING(name, 1, POSITION(' and ' IN name || ' and ') - 1),
        SUBSTRING(name, POSITION(' and ' IN name || ' and ') + 5)
    FROM tmp

    WHERE name > ''
) SELECT years, winner, producers FROM tmp;

--> AWARDS TABLE
CREATE TABLE AWARDS AS WITH tmp(years, winner, producers, name) AS
(
    SELECT
        YEARS,
        WINNER,
        SUBSTRING(producers, 1, POSITION(', ' IN producers || ', ') - 1),
        SUBSTRING(producers, POSITION(', ' IN producers || ', ') + 2)
    FROM temp_table WHERE winner = 'yes'

    UNION ALL

    SELECT
        YEARS,
        WINNER,
        SUBSTRING(name, 1, POSITION(', ' IN name || ', ') - 1),
        SUBSTRING(name, POSITION(', ' IN name || ', ') + 2)
    FROM tmp

    WHERE name > ''
) SELECT years, winner, producers FROM tmp;
ALTER TABLE awards ADD COLUMN ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
DROP TABLE temp_table;
