DROP TABLE IF EXISTS movie;
CREATE TABLE movie (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    YEARS INTEGER,
    TITLE VARCHAR(255),
    STUDIOS VARCHAR(255),
    PRODUCERS VARCHAR(255),
    WINNER VARCHAR(255)
);
INSERT INTO movie (YEARS, TITLE, STUDIOS, PRODUCERS, WINNER) SELECT * FROM CSVREAD('classpath:init/movie.csv', null, 'fieldSeparator=;');

UPDATE movie SET winner = 1 WHERE winner = 'yes';
UPDATE movie SET winner = 0 WHERE winner IS NULL;

DROP TABLE IF EXISTS producer;
CREATE TABLE producer AS SELECT DISTINCT producers FROM movie;
ALTER TABLE producer ADD COLUMN ID BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL NOT NULL FIRST;
ALTER TABLE producer ADD COLUMN min_interval INTEGER;
ALTER TABLE producer ADD COLUMN max_interval INTEGER;
ALTER TABLE producer ADD COLUMN min_previous_year INTEGER;
ALTER TABLE producer ADD COLUMN min_following_year INTEGER;
ALTER TABLE producer ADD COLUMN max_previous_year INTEGER;
ALTER TABLE producer ADD COLUMN max_following_year INTEGER;

UPDATE movie SET producers = (SELECT ID FROM producer WHERE producer.producers = movie.producers);

DROP TABLE IF EXISTS studio;
CREATE TABLE studio AS SELECT DISTINCT studios FROM movie;
ALTER TABLE studio ADD COLUMN ID BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL NOT NULL FIRST;

UPDATE movie SET studios = (SELECT ID FROM studio WHERE studio.studios = movie.studios);

with producer_intervals as (
    SELECT producers, (years - LAG(years) OVER (PARTITION BY producers ORDER BY years)) as x_interval,
    years,
    LAG(years, 1) OVER (PARTITION BY producers ORDER BY years) as prev_years,
    FROM movie WHERE producers IN (SELECT producers FROM movie WHERE winner = 1 GROUP BY producers HAVING COUNT(producers) > 1) ORDER BY producers, years
) UPDATE producer SET
min_interval = (SELECT MIN(x_interval) FROM producer_intervals WHERE producer_intervals.producers = producer.ID),
max_interval = (SELECT MAX(x_interval) FROM producer_intervals WHERE producer_intervals.producers = producer.ID),
min_previous_year = (SELECT prev_years FROM producer_intervals WHERE producer_intervals.producers = producer.ID
    AND x_interval = (SELECT MIN(x_interval) FROM producer_intervals WHERE producer_intervals.producers = producer.ID)),
min_following_year = (SELECT years FROM producer_intervals WHERE producer_intervals.producers = producer.ID
    AND x_interval = (SELECT MIN(x_interval) FROM producer_intervals WHERE producer_intervals.producers = producer.ID)),
max_previous_year = (SELECT prev_years FROM producer_intervals WHERE producer_intervals.producers = producer.ID
    AND x_interval = (SELECT MAX(x_interval) FROM producer_intervals WHERE producer_intervals.producers = producer.ID)),
max_following_year = (SELECT years FROM producer_intervals WHERE producer_intervals.producers = producer.ID
    AND x_interval = (SELECT MAX(x_interval) FROM producer_intervals WHERE producer_intervals.producers = producer.ID));
